version: '3.7'

services:
  lighthouse:
    image: petabridge/lighthouse:latest
    hostname: lighthouse
    ports:
      - '9110:9110'
      - '4053:4053'
    environment:
      ACTORSYSTEM: "Akka-Cluster"
      CLUSTER_PORT: 4053
      CLUSTER_IP: "lighthouse"
      CLUSTER_SEEDS: "akka.tcp://Akka-Cluster@lighthouse:4053"

  engine0:
    image: engine
    ports:
      - '6000:9110'
    environment:
      CLUSTER_SEEDS: "akka.tcp://Akka-Cluster@lighthouse:4053"
      CLUSTER_PORT: 5110
    restart: on-failure
    depends_on:
      - "lighthouse"

  engine1:
    image: engine
    ports:
      - '6001:9110'
    environment:
      CLUSTER_SEEDS: "akka.tcp://Akka-Cluster@lighthouse:4053"
      CLUSTER_PORT: 5110
    restart: on-failure
    depends_on:
      - "lighthouse"

  engine2:
    image: engine
    ports:
      - '6002:9110'
    environment:
      CLUSTER_SEEDS: "akka.tcp://Akka-Cluster@lighthouse:4053"
      CLUSTER_PORT: 5110
    restart: on-failure
    depends_on:
      - "lighthouse"

  engine3:
    image: engine
    ports:
      - '6003:9110'
    environment:
      CLUSTER_SEEDS: "akka.tcp://Akka-Cluster@lighthouse:4053"
      CLUSTER_PORT: 5110
    restart: on-failure
    depends_on:
      - "lighthouse"

  web0:
    image: web
    container_name: "frontend1"
    ports:
      - "7000:9110"
      - "8080:80"
      - "8090:443"
    environment:
      CLUSTER_SEEDS: "akka.tcp://Akka-Cluster@lighthouse:4053"
      CLUSTER_PORT: 5110
    restart: on-failure
    depends_on:
      - "lighthouse"

  web1:
    image: web
    container_name: "frontend2"
    ports:
      - "7001:9110"
      - "8081:80"
      - "8091:443"
    environment:
      CLUSTER_SEEDS: "akka.tcp://Akka-Cluster@lighthouse:4053"
      CLUSTER_PORT: 5110
    restart: on-failure
    depends_on:
      - "lighthouse"

  web2:
    image: web
    container_name: "frontend3"
    ports:
      - "7002:9110"
      - "8082:80"
      - "8092:443"
    environment:
      CLUSTER_SEEDS: "akka.tcp://Akka-Cluster@lighthouse:4053"
      CLUSTER_PORT: 5110
    restart: on-failure
    depends_on:
      - "lighthouse"

  proxy:  
    image: nginx 
    container_name: "api"
    ports:   
    - "5000:80"
    depends_on:
      - web0
      - web1
      - web2

  master:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./Build/locust/:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master --logfile=locustfile.log

  worker1:
    image: locustio/locust
    volumes:
      - ./Build/locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master --logfile=locustfile.log

  worker2:
    image: locustio/locust
    volumes:
      - ./Build/locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master --logfile=locustfile.log
